---
- name: Install Kubernetes
  hosts: kubernetes
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Remove old Kubernetes APT repository
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/deb/ /"
        state: present

    - name: Download Kubernetes APT key
      command: curl -fsSL https://pkgs.k8s.io/core:/stable:/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kubernetes
      apt:
        name: ['kubelet', 'kubeadm', 'kubectl']
        state: present
        update_cache: yes

    - name: Initialize Kubernetes Master
      command: kubeadm init
      when: inventory_hostname == 'k8master'

    - name: Join Kubernetes Node
      command: kubeadm join <MASTER_IP>:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH>
      when: inventory_hostname != 'k8master'
